; ..\X86\api-ms-win-net-isolation-l1-1-0.lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

DelayLoad_SetLastNtStatusAndWin32Error PROTO
NetworkIsolationDiagnoseConnectFailureAndGetInfo PROTO :DWORD,:DWORD
NetworkIsolationEnumAppContainers PROTO :DWORD,:DWORD,:DWORD
NetworkIsolationFreeAppContainers PROTO :DWORD
NetworkIsolationGetAppContainerConfig PROTO :DWORD,:DWORD
NetworkIsolationRegisterForAppContainerChanges PROTO :DWORD,:DWORD,:DWORD,:DWORD
NetworkIsolationSetAppContainerConfig PROTO :DWORD,:DWORD
NetworkIsolationSetupAppContainerBinaries PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
NetworkIsolationUnregisterForAppContainerChanges PROTO :DWORD
api_ms_win_net_isolation_l1_1_0_NetworkIsolationDiagnoseConnectFailureAndGetInfo PROTO :DWORD,:DWORD
api_ms_win_net_isolation_l1_1_0_NetworkIsolationEnumAppContainers PROTO :DWORD,:DWORD,:DWORD
api_ms_win_net_isolation_l1_1_0_NetworkIsolationFreeAppContainers PROTO :DWORD
api_ms_win_net_isolation_l1_1_0_NetworkIsolationGetAppContainerConfig PROTO :DWORD,:DWORD
api_ms_win_net_isolation_l1_1_0_NetworkIsolationRegisterForAppContainerChanges PROTO :DWORD,:DWORD,:DWORD,:DWORD
api_ms_win_net_isolation_l1_1_0_NetworkIsolationSetAppContainerConfig PROTO :DWORD,:DWORD
api_ms_win_net_isolation_l1_1_0_NetworkIsolationSetupAppContainerBinaries PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
api_ms_win_net_isolation_l1_1_0_NetworkIsolationUnregisterForAppContainerChanges PROTO :DWORD

