; ..\X86\ComDlg32.Lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ChooseColorA PROTO :DWORD
ChooseColor equ <ChooseColorA>

ChooseFontA PROTO :DWORD
ChooseFont equ <ChooseFontA>

CommDlgExtendedError PROTO
FindTextA PROTO :DWORD
FindText equ <FindTextA>

GetFileTitleA PROTO :DWORD,:DWORD,:DWORD
GetFileTitle equ <GetFileTitleA>

GetOpenFileNameA PROTO :DWORD
GetOpenFileName equ <GetOpenFileNameA>

GetSaveFileNameA PROTO :DWORD
GetSaveFileName equ <GetSaveFileNameA>

PageSetupDlgA PROTO :DWORD
PageSetupDlg equ <PageSetupDlgA>

PrintDlgA PROTO :DWORD
PrintDlg equ <PrintDlgA>

PrintDlgExA PROTO :DWORD
PrintDlgEx equ <PrintDlgExA>

ReplaceTextA PROTO :DWORD
ReplaceText equ <ReplaceTextA>


