; ..\X86\drtprov.lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

DrtCreateDerivedKey PROTO :DWORD,:DWORD
DrtCreateDerivedKeySecurityProvider PROTO :DWORD,:DWORD,:DWORD
DrtCreateDnsBootstrapResolver PROTO :DWORD,:DWORD,:DWORD
DrtCreateNullSecurityProvider PROTO :DWORD
DrtCreatePnrpBootstrapResolver PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
DrtDeleteDerivedKeySecurityProvider PROTO :DWORD
DrtDeleteDnsBootstrapResolver PROTO :DWORD
DrtDeleteNullSecurityProvider PROTO :DWORD
DrtDeletePnrpBootstrapResolver PROTO :DWORD

