; ..\X86\DSProp.Lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ADsPropCheckIfWritable PROTO :DWORD,:DWORD
ADsPropCreateNotifyObj PROTO :DWORD,:DWORD,:DWORD
ADsPropGetInitInfo PROTO :DWORD,:DWORD
ADsPropSendErrorMessage PROTO :DWORD,:DWORD
ADsPropSetHwnd PROTO :DWORD,:DWORD
ADsPropSetHwndWithTitle PROTO :DWORD,:DWORD,:DWORD
ADsPropShowErrorDialog PROTO :DWORD,:DWORD
BringSheetToForeground PROTO :DWORD,:DWORD
IsSheetAlreadyUp PROTO :DWORD
PostADsPropSheet PROTO :DWORD,:DWORD,:DWORD,:DWORD

