; ..\X86\KSProxy.Lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

KsGetMediaType PROTO :DWORD,:DWORD,:DWORD,:DWORD
KsGetMediaTypeCount PROTO :DWORD,:DWORD,:DWORD
KsGetMultiplePinFactoryItems PROTO :DWORD,:DWORD,:DWORD,:DWORD
KsOpenDefaultDevice PROTO :DWORD,:DWORD,:DWORD
KsResolveRequiredAttributes PROTO :DWORD,:DWORD
KsSynchronousDeviceControl PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD

