; ..\X86\magnification.lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

MagGetColorEffect PROTO :DWORD,:DWORD
MagGetFullscreenColorEffect PROTO :DWORD
MagGetFullscreenTransform PROTO :DWORD,:DWORD,:DWORD
MagGetImageScalingCallback PROTO :DWORD
MagGetInputTransform PROTO :DWORD,:DWORD,:DWORD
MagGetWindowFilterList PROTO :DWORD,:DWORD,:DWORD,:DWORD
MagGetWindowSource PROTO :DWORD,:DWORD
MagGetWindowTransform PROTO :DWORD,:DWORD
MagInitialize PROTO
MagSetColorEffect PROTO :DWORD,:DWORD
MagSetFullscreenColorEffect PROTO :DWORD
MagSetFullscreenTransform PROTO :DWORD,:DWORD,:DWORD
MagSetImageScalingCallback PROTO :DWORD,:DWORD
MagSetInputTransform PROTO :DWORD,:DWORD,:DWORD
MagSetWindowFilterList PROTO :DWORD,:DWORD,:DWORD,:DWORD
MagSetWindowSource PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
MagSetWindowTransform PROTO :DWORD,:DWORD
MagShowSystemCursor PROTO :DWORD
MagUninitialize PROTO

