; ..\X86\MMC.Lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~

MMCAfxPropPageCallback PROTO :DWORD,:DWORD
MMCFreeNotifyHandle PROTO :DWORD
MMCIsMTNodeValid PROTO :DWORD,:DWORD
MMCPropPageCallback PROTO :DWORD
MMCPropertyChangeNotify PROTO :DWORD,:DWORD
MMCPropertyHelp PROTO :DWORD
_guard_fids__MMCAfxPropPageCallback PROTO :DWORD,:DWORD
_guard_fids__MMCPropPageCallback PROTO :DWORD
_security_check_cookie PROTO :DWORD
guard_check_icall PROTO :DWORD
guard_check_icall_nop PROTO :DWORD

