; ..\X86\msports.lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ComDBClaimNextFreePort PROTO :DWORD,:DWORD
ComDBClaimPort PROTO :DWORD,:DWORD,:DWORD,:DWORD
ComDBClose PROTO :DWORD
ComDBGetCurrentPortUsage PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
ComDBOpen PROTO :DWORD
ComDBReleasePort PROTO :DWORD,:DWORD
ComDBResizeDatabase PROTO :DWORD,:DWORD
ParallelPortPropPageProvider PROTO :DWORD,:DWORD,:DWORD
PortsClassInstaller PROTO :DWORD,:DWORD,:DWORD
SerialDisplayAdvancedSettings PROTO :DWORD,:DWORD,:DWORD
SerialPortPropPageProvider PROTO :DWORD,:DWORD,:DWORD

