; ..\X86\MSRating.Lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ChangeSupervisorPassword PROTO :DWORD,:DWORD
ClickedOnPRF PROTO :DWORD,:DWORD,:DWORD,:DWORD
ClickedOnRAT PROTO :DWORD,:DWORD,:DWORD,:DWORD
RatingAccessDeniedDialog PROTO :DWORD,:DWORD,:DWORD,:DWORD
RatingAccessDeniedDialog2 PROTO :DWORD,:DWORD,:DWORD
RatingAddPropertyPages PROTO :DWORD,:DWORD,:DWORD
RatingAddToApprovedSites PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
RatingCheckUserAccess PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
RatingClickedOnPRFInternal PROTO :DWORD,:DWORD,:DWORD,:DWORD
RatingClickedOnRATInternal PROTO :DWORD,:DWORD,:DWORD,:DWORD
RatingCustomAddRatingHelper PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
RatingCustomAddRatingSystem PROTO :DWORD,:DWORD
RatingCustomCrackData PROTO :DWORD,:DWORD,:DWORD
RatingCustomDeleteCrackedData PROTO :DWORD
RatingCustomInit PROTO :DWORD
RatingCustomRemoveRatingHelper PROTO :DWORD,:DWORD,:DWORD,:DWORD
RatingCustomSetDefaultBureau PROTO :DWORD
RatingCustomSetUserOptions PROTO :DWORD,:DWORD
RatingEnable PROTO :DWORD,:DWORD,:DWORD
RatingEnabledQuery PROTO
RatingFreeDetails PROTO :DWORD
RatingInit PROTO
RatingObtainCancel PROTO :DWORD
RatingObtainQuery PROTO :DWORD,:DWORD,:DWORD,:DWORD
RatingSetupUI PROTO :DWORD,:DWORD
VerifySupervisorPassword PROTO :DWORD

