; ..\X86\ninput.lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

AddPointerInteractionContext PROTO :DWORD,:DWORD
BufferPointerPacketsInteractionContext PROTO :DWORD,:DWORD,:DWORD
CreateInteractionContext PROTO :DWORD
DestroyInteractionContext PROTO :DWORD
GetCrossSlideParameterInteractionContext PROTO :DWORD,:DWORD,:DWORD
GetInertiaParameterInteractionContext PROTO :DWORD,:DWORD,:DWORD
GetInteractionConfigurationInteractionContext PROTO :DWORD,:DWORD,:DWORD
GetMouseWheelParameterInteractionContext PROTO :DWORD,:DWORD,:DWORD
GetPropertyInteractionContext PROTO :DWORD,:DWORD,:DWORD
GetStateInteractionContext PROTO :DWORD,:DWORD,:DWORD
ProcessBufferedPacketsInteractionContext PROTO :DWORD
ProcessInertiaInteractionContext PROTO :DWORD
ProcessPointerFramesInteractionContext PROTO :DWORD,:DWORD,:DWORD,:DWORD
RegisterOutputCallbackInteractionContext PROTO :DWORD,:DWORD,:DWORD
RemovePointerInteractionContext PROTO :DWORD,:DWORD
ResetInteractionContext PROTO :DWORD
SetCrossSlideParametersInteractionContext PROTO :DWORD,:DWORD,:DWORD
SetInertiaParameterInteractionContext PROTO :DWORD,:DWORD,:DWORD
SetInteractionConfigurationInteractionContext PROTO :DWORD,:DWORD,:DWORD
SetMouseWheelParameterInteractionContext PROTO :DWORD,:DWORD,:DWORD
SetPivotInteractionContext PROTO :DWORD,:DWORD,:DWORD,:DWORD
SetPropertyInteractionContext PROTO :DWORD,:DWORD,:DWORD
StopInteractionContext PROTO :DWORD

