; ..\X86\pathcch.lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

PathAllocCanonicalize PROTO :DWORD,:DWORD,:DWORD
PathAllocCombine PROTO :DWORD,:DWORD,:DWORD,:DWORD
PathCchAddBackslash PROTO :DWORD,:DWORD
PathCchAddBackslashEx PROTO :DWORD,:DWORD,:DWORD,:DWORD
PathCchAddExtension PROTO :DWORD,:DWORD,:DWORD
PathCchAppend PROTO :DWORD,:DWORD,:DWORD
PathCchAppendEx PROTO :DWORD,:DWORD,:DWORD,:DWORD
PathCchCanonicalize PROTO :DWORD,:DWORD,:DWORD
PathCchCanonicalizeEx PROTO :DWORD,:DWORD,:DWORD,:DWORD
PathCchCombine PROTO :DWORD,:DWORD,:DWORD,:DWORD
PathCchCombineEx PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
PathCchFindExtension PROTO :DWORD,:DWORD,:DWORD
PathCchIsRoot PROTO :DWORD
PathCchRemoveBackslash PROTO :DWORD,:DWORD
PathCchRemoveBackslashEx PROTO :DWORD,:DWORD,:DWORD,:DWORD
PathCchRemoveExtension PROTO :DWORD,:DWORD
PathCchRemoveFileSpec PROTO :DWORD,:DWORD
PathCchRenameExtension PROTO :DWORD,:DWORD,:DWORD
PathCchSkipRoot PROTO :DWORD,:DWORD
PathCchStripPrefix PROTO :DWORD,:DWORD
PathCchStripToRoot PROTO :DWORD,:DWORD
PathIsUNCEx PROTO :DWORD,:DWORD

