; ..\X86\sbtsv.lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~

BSTR_UserFree PROTO :DWORD,:DWORD
BSTR_UserMarshal PROTO :DWORD,:DWORD,:DWORD
BSTR_UserSize PROTO :DWORD,:DWORD,:DWORD
BSTR_UserUnmarshal PROTO :DWORD,:DWORD,:DWORD
CStdStubBuffer2_Release PROTO :DWORD
CStdStubBuffer_AddRef PROTO :DWORD
CStdStubBuffer_Connect PROTO :DWORD,:DWORD
CStdStubBuffer_CountRefs PROTO :DWORD
CStdStubBuffer_DebugServerQueryInterface PROTO :DWORD,:DWORD
CStdStubBuffer_DebugServerRelease PROTO :DWORD,:DWORD
CStdStubBuffer_Disconnect PROTO :DWORD
CStdStubBuffer_Invoke PROTO :DWORD,:DWORD,:DWORD
CStdStubBuffer_IsIIDSupported PROTO :DWORD,:DWORD
CStdStubBuffer_QueryInterface PROTO :DWORD,:DWORD,:DWORD
CStdStubBuffer_Release PROTO :DWORD
IUnknown_AddRef_Proxy PROTO :DWORD
IUnknown_QueryInterface_Proxy PROTO :DWORD,:DWORD,:DWORD
IUnknown_Release_Proxy PROTO :DWORD
LPSAFEARRAY_UserFree PROTO :DWORD,:DWORD
LPSAFEARRAY_UserMarshal PROTO :DWORD,:DWORD,:DWORD
LPSAFEARRAY_UserSize PROTO :DWORD,:DWORD,:DWORD
LPSAFEARRAY_UserUnmarshal PROTO :DWORD,:DWORD,:DWORD
NdrOleAllocate PROTO :DWORD
NdrOleFree PROTO :DWORD
NdrProxyForwardingFunction3 PROTO
NdrProxyForwardingFunction4 PROTO
NdrProxyForwardingFunction8 PROTO
NdrStubCall2 PROTO :DWORD,:DWORD,:DWORD,:DWORD
NdrStubForwardingFunction PROTO :DWORD,:DWORD,:DWORD,:DWORD
ObjectStublessClient10 PROTO
ObjectStublessClient11 PROTO
ObjectStublessClient12 PROTO
ObjectStublessClient13 PROTO
ObjectStublessClient14 PROTO
ObjectStublessClient15 PROTO
ObjectStublessClient16 PROTO
ObjectStublessClient17 PROTO
ObjectStublessClient18 PROTO
ObjectStublessClient19 PROTO
ObjectStublessClient20 PROTO
ObjectStublessClient21 PROTO
ObjectStublessClient22 PROTO
ObjectStublessClient3 PROTO
ObjectStublessClient4 PROTO
ObjectStublessClient5 PROTO
ObjectStublessClient6 PROTO
ObjectStublessClient7 PROTO
ObjectStublessClient8 PROTO
ObjectStublessClient9 PROTO
VARIANT_UserFree PROTO :DWORD,:DWORD
VARIANT_UserMarshal PROTO :DWORD,:DWORD,:DWORD
VARIANT_UserSize PROTO :DWORD,:DWORD,:DWORD
VARIANT_UserUnmarshal PROTO :DWORD,:DWORD,:DWORD
_sbtsv_IID_Lookup PROTO :DWORD,:DWORD

