; ..\X86\sisbkup.lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SisCSFilesToBackupForLink PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
SisCreateBackupStructure PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
SisCreateRestoreStructure PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
SisFreeAllocatedMemory PROTO :DWORD
SisFreeBackupStructure PROTO :DWORD
SisFreeRestoreStructure PROTO :DWORD
SisRestoredCommonStoreFile PROTO :DWORD,:DWORD
SisRestoredLink PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD

