; ..\X86\tspubplugincom.lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

BSTR_UserFree PROTO :DWORD,:DWORD
BSTR_UserMarshal PROTO :DWORD,:DWORD,:DWORD
BSTR_UserSize PROTO :DWORD,:DWORD,:DWORD
BSTR_UserUnmarshal PROTO :DWORD,:DWORD,:DWORD
CStdStubBuffer2_Release PROTO :DWORD
CStdStubBuffer_AddRef PROTO :DWORD
CStdStubBuffer_Connect PROTO :DWORD,:DWORD
CStdStubBuffer_CountRefs PROTO :DWORD
CStdStubBuffer_DebugServerQueryInterface PROTO :DWORD,:DWORD
CStdStubBuffer_DebugServerRelease PROTO :DWORD,:DWORD
CStdStubBuffer_Disconnect PROTO :DWORD
CStdStubBuffer_Invoke PROTO :DWORD,:DWORD,:DWORD
CStdStubBuffer_IsIIDSupported PROTO :DWORD,:DWORD
CStdStubBuffer_QueryInterface PROTO :DWORD,:DWORD,:DWORD
CStdStubBuffer_Release PROTO :DWORD
DllCanUnloadNow PROTO
DllGetClassObject PROTO :DWORD,:DWORD,:DWORD
GetProxyDllInfo PROTO :DWORD,:DWORD
IUnknown_AddRef_Proxy PROTO :DWORD
IUnknown_QueryInterface_Proxy PROTO :DWORD,:DWORD,:DWORD
IUnknown_Release_Proxy PROTO :DWORD
NdrCStdStubBuffer2_Release PROTO :DWORD,:DWORD
NdrCStdStubBuffer_Release PROTO :DWORD,:DWORD
NdrOleAllocate PROTO :DWORD
NdrOleFree PROTO :DWORD
NdrProxyForwardingFunction3 PROTO
NdrProxyForwardingFunction4 PROTO
NdrProxyForwardingFunction5 PROTO
NdrProxyForwardingFunction6 PROTO
NdrProxyForwardingFunction7 PROTO
NdrProxyForwardingFunction8 PROTO
NdrStubCall2 PROTO :DWORD,:DWORD,:DWORD,:DWORD
NdrStubForwardingFunction PROTO :DWORD,:DWORD,:DWORD,:DWORD
ObjectStublessClient10 PROTO
ObjectStublessClient11 PROTO
ObjectStublessClient12 PROTO
ObjectStublessClient3 PROTO
ObjectStublessClient4 PROTO
ObjectStublessClient5 PROTO
ObjectStublessClient6 PROTO
ObjectStublessClient7 PROTO
ObjectStublessClient8 PROTO
ObjectStublessClient9 PROTO
_tspubplugin2com_IID_Lookup PROTO :DWORD,:DWORD
_tspubplugincom_IID_Lookup PROTO :DWORD,:DWORD

