; ..\X86\wdsbp.lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~

WdsBpAddOption PROTO :DWORD,:DWORD,:DWORD,:DWORD
WdsBpCloseHandle PROTO :DWORD
WdsBpGetOptionBuffer PROTO :DWORD,:DWORD,:DWORD,:DWORD
WdsBpInitialize PROTO :DWORD,:DWORD
WdsBpParseInitialize PROTO :DWORD,:DWORD,:DWORD,:DWORD
WdsBpParseInitializev6 PROTO :DWORD,:DWORD,:DWORD,:DWORD
WdsBpQueryOption PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD

