; ..\X86\workspaceax.lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

BSTR_UserFree PROTO :DWORD,:DWORD
BSTR_UserMarshal PROTO :DWORD,:DWORD,:DWORD
BSTR_UserSize PROTO :DWORD,:DWORD,:DWORD
BSTR_UserUnmarshal PROTO :DWORD,:DWORD,:DWORD
CStdStubBuffer2_Release PROTO :DWORD
CStdStubBuffer_AddRef PROTO :DWORD
CStdStubBuffer_Connect PROTO :DWORD,:DWORD
CStdStubBuffer_CountRefs PROTO :DWORD
CStdStubBuffer_DebugServerQueryInterface PROTO :DWORD,:DWORD
CStdStubBuffer_DebugServerRelease PROTO :DWORD,:DWORD
CStdStubBuffer_Disconnect PROTO :DWORD
CStdStubBuffer_Invoke PROTO :DWORD,:DWORD,:DWORD
CStdStubBuffer_IsIIDSupported PROTO :DWORD,:DWORD
CStdStubBuffer_QueryInterface PROTO :DWORD,:DWORD,:DWORD
CStdStubBuffer_Release PROTO :DWORD
IUnknown_AddRef_Proxy PROTO :DWORD
IUnknown_QueryInterface_Proxy PROTO :DWORD,:DWORD,:DWORD
IUnknown_Release_Proxy PROTO :DWORD
LPSAFEARRAY_UserFree PROTO :DWORD,:DWORD
LPSAFEARRAY_UserMarshal PROTO :DWORD,:DWORD,:DWORD
LPSAFEARRAY_UserSize PROTO :DWORD,:DWORD,:DWORD
LPSAFEARRAY_UserUnmarshal PROTO :DWORD,:DWORD,:DWORD
NdrOleAllocate PROTO :DWORD
NdrOleFree PROTO :DWORD
NdrStubCall2 PROTO :DWORD,:DWORD,:DWORD,:DWORD
NdrStubForwardingFunction PROTO :DWORD,:DWORD,:DWORD,:DWORD
_radcapi_IID_Lookup PROTO :DWORD,:DWORD
_workspaceax_IID_Lookup PROTO :DWORD,:DWORD
_workspacenotify_IID_Lookup PROTO :DWORD,:DWORD

