; ..\X86\xmllite.lib PROTOTYPES
; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CreateXmlReader PROTO :DWORD,:DWORD,:DWORD
CreateXmlReaderInputWithEncodingCodePage PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
CreateXmlReaderInputWithEncodingName PROTO :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
CreateXmlWriter PROTO :DWORD,:DWORD,:DWORD
CreateXmlWriterOutputWithEncodingCodePage PROTO :DWORD,:DWORD,:DWORD,:DWORD
CreateXmlWriterOutputWithEncodingName PROTO :DWORD,:DWORD,:DWORD,:DWORD

